### ISSUE TITLE
Hello (just a fun issue)

### ISSUE THREAD

**Issue by usefss** [MR-SS/XO-game#1]
why this game bro?
if you want it just [google](https://www.google.com/search?biw=1536&bih=742&sxsrf=ALeKk01qKJOQXslmR-KYmMziz4EmUeYvKQ%3A1602501795687&ei=ozyEX4mxKdam1fAP36i--Ac&q=xo+game&oq=xo+game&gs_lcp=CgZwc3ktYWIQAzIECAAQRzIECAAQRzIECAAQRzIECAAQRzIECAAQRzIECAAQRzIECAAQRzIECAAQR1CSCFiSCGDPCWgAcAJ4AIABAIgBAJIBAJgBAKABAaoBB2d3cy13aXrIAQjAAQE&sclient=psy-ab&ved=0ahUKEwjJjqKy-K7sAhVWUxUIHV-UD38Q4dUDCA0&uact=5) it!!

**Comment by MR-SS** [comment]
take it  easy dude. i'm not  you !!! it's for practicing dude
